# name: ESLint
#
# on:
#   pull_request:
#   push:
#     branches: [main]
#
# concurrency:
#   group: eslint-${{ github.ref }}
#   cancel-in-progress: true
#
# jobs:
#   lint:
#     uses: ./.github/workflows/_base.yml
#     with:
#       run: bun run lint
